language: scala
dist: trusty
sudo: false
scala:
  - 2.11.11
  - 2.12.7
cache:
  directories:
    - '$HOME/node_modules'
    - $HOME/.ivy2
services:
  - mongodb
jdk:
  - oraclejdk8
matrix:
  include:
  - scala: 2.12.7
    jdk: oraclejdk11
script: ./travis.sh
branches:
  only:
    - master
    - /^release-branch-.*$/
node_js:
  - "4.1"
before_script:
  - "cd web/webkit"
  - "npm install"
  - "cd -"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/85e4d8ae84e569f9c501
    on_success: always
    on_failure: always
    on_start: never
  email:
    recipients:
      - lift-committers@googlegroups.com
    on_success: change
    on_failure: always
