language: scala
cache:
  directories:
    - '$HOME/node_modules'
services:
  - mongodb
jdk:
  - oraclejdk7

script: ./travis.sh

branches:
  only:
    - master

node_js:
  - "4.1"

before_script:
  - "cd web/webkit"
  - "npm set progress=false"
  - "npm install"
  - "cd -"
